services:
  minio:
    image: quay.io/minio/minio
    ports:
      - "9000:9000"
      - "9001:9001" # Web UI
    env_file:
      - .env
    environment:
      MINIO_ROOT_USER: ${MINIO_ACCESS_KEY:-minioadmin}
      MINIO_ROOT_PASSWORD: ${MINIO_SECRET_KEY:-minioadmin}
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 5s
      timeout: 20s
      retries: 3
      start_period: 10s

  api:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - MINIO_ENDPOINT=minio:9000
      - NODE_ENV=production
    volumes:
      - ./:/app
      - node_modules:/app/node_modules
    depends_on:
      minio:
        condition: service_healthy
    restart: unless-stopped

volumes:
  minio_data:
  node_modules:
